AllCops:
  TargetRubyVersion: 2.6

Style/Documentation:
  Enabled: false

Metrics/AbcSize:
  Max: 25

Metrics/LineLength:
  Max: 130

Metrics/MethodLength:
  Max: 20

Metrics/BlockLength:
  Max: 40

Metrics/ClassLength:
  Max: 150

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/EmptyLinesAroundModuleBody:
  EnforcedStyle: empty_lines

Style/SignalException:
  EnforcedStyle: only_raise

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma

Style/FrozenStringLiteralComment:
  Enabled: true

Style/TrivialAccessors:
  ExactNameMatch: true
